# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      # - id: pretty-format-json
      - id: end-of-file-fixer
        exclude: .svg$
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: .svg$
      - id: check-case-conflict
      - id: check-merge-conflict
  # - repo: https://github.com/ansible/ansible-lint.git
  #   rev: v4.3.7
  #   hooks:
  #     - id: ansible-lint
  #       name: Ansible-lint
  #       description: This hook runs ansible-lint.
  #       entry: ansible-lint
  #       language: python
  #       # do not pass files to ansible-lint, see:
  #       # https://github.com/ansible/ansible-lint/issues/611
  #       always_run: true
  #       pass_filenames: false
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint -c .yamllint.yml --strict
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
