---
extends: default

ignore: |
  .pre-commit-config.yaml
  .gitlab-ci.yml
  .yamllint.yml
  docker-compose.yml

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 150
    level: warning

  # accept both     key:
  #                   - item
  #
  # and             key:
  #                 - item
  indentation:
    indent-sequences: whatever
